services:
  nats:
    image: nats:2.12.3-alpine3.22
    container_name: uploader-queue
    ports:
      - "${NATS_PORT}:4222"
    environment:
      - NATS_PORT=${NATS_PORT}
    restart: unless-stopped
