@api_host = http://localhost:8080
@device_id = testDevice123

### Post Event Reading
POST {{api_host}}/sysinfo
Content-Type: application/json

{
  "mac_address": "00:11:22:33:44:55",
  "read_time": 1678886400000,
  "metrics": {
    "temperature": 22.1,
    "humidity": 65.3,
    "pressure": 1012.5
  }
}
